import Head from "next/head";
const HomeSeo = () => (
    <Head>
        <title>ManOrInfinity</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favico.svg" />
      </Head>
)
export default HomeSeo;